### ISSUE TITLE
Html reporter can have trouble with binary files

### ISSUE THREAD

**Issue by benpatterson** [Bachmann1234/diff-cover#4] opened 2015-02-09 20:34 UTC
Hi! - I spent a bit time looking at this today, but unfortunately I'm out of time.

We had a PR today ( edx/edx-platform#6921 ) which introduced some binary files (including .bcmap and .png). These ended up causing failures when running diff-quality with the --html-report flag. (Without the flag, there are no errors). See console output here: https://build.testeng.edx.org/job/edx-platform-all-tests-pr/1202/SHARD=1,TEST_SUITE=quality,label_exp=jenkins-worker/console

Unfo it is a large commit and I was unable to isolate the offending file(s). I did attempt to reproduce this problem locally by creating a .bin and a .tar file, but I was unable to reproduce the error :( Thought, at best, I could log it here.

**Comment by sarina** [comment] 2015-02-17 21:38
@Bachmann1234 do you have any idea how we might fix this? It's blocking some work for us, since it's borking the build (ref https://github.com/edx/edx-platform/pull/6921 )

**Comment by Bachmann1234** [comment] 2015-02-17 21:44
@sarina oh jeez I had not fully grasp this was blocking and have not given this much time yet. Ill dig into this tonight.

**Comment by sarina** [comment] 2015-02-17 21:47
@Bachmann1234 I might be able to give it some time in a few days, if you can't. Just wondering if you have a thought at where to start... heh.

**Comment by Bachmann1234** [comment] 2015-02-17 22:03
Well ill give you my theory then.

So this explodes here: https://github.com/Bachmann1234/diff-cover/blob/master/diff_cover/snippets.py#L155

And it explodes trying to decode utf-8 output

What this tells me as that ```detect_encoding``` is detecting utf-8 but the encoding is something else. 

There might be a way of checking the metadata of the file to see what encoding it was saved in... but more likely we still have to guess.

Since I don't think we can actually know the encoding of the file for sure the next best thing would be to throw UnicodeDammit from http://www.crummy.com/software/BeautifulSoup/bs4/doc/ at it. It tends to do pretty well. If you end up doing this just make sure to add chardet to the requirements as well as BS4 will not include it by default and this will lead to weaker encoding sniffing.

**Comment by Bachmann1234** [comment] 2015-02-17 22:08
Of course... if it is a binary file any encoding would be wrong and we should not include it in the report

**Comment by sarina** [comment] 2015-02-17 22:09
Yeah - I think that's the solution I really want, to just *not* try to run diff-cover on a binary file... :disappointed:

**Comment by Bachmann1234** [comment] 2015-02-17 22:10
@sarina yep, to reproduce this I would look at the bcmap files in pdf.js. thats my hunch

**Comment by Bachmann1234** [comment] 2015-02-17 22:21
Oh and one more thing. I checked out that branch just now and ran git stat on it to see the files that changed as github was chocking under the load.

https://gist.github.com/Bachmann1234/cb957e80010b0e063a05

No python files. Unless i'm missing something the real question may be how pep8 found a violation to include in a snippet in the first place

**Comment by Bachmann1234** [comment] 2015-02-18 00:34
@sarina im having trouble reproducing this
If you get stuck can you get me these pep8 reports?
```
/home/jenkins/workspace/edx-platform-all-tests-pr/SHARD/1/TEST_SUITE/quality/label_exp/jenkins-worker/reports/cms/pep8.report /home/jenkins/workspace/edx-platform-all-tests-pr/SHARD/1/TEST_SUITE/quality/label_exp/jenkins-worker/reports/lms/pep8.report /home/jenkins/workspace/edx-platform-all-tests-pr/SHARD/1/TEST_SUITE/quality/label_exp/jenkins-worker/reports/common/pep8.report
```

**Comment by benpatterson** [comment] 2015-02-18 00:47
@Bachmann1234 @sarina For what it's worth, when I was reproducing this on the affected branch a couple of weeks ago, diff-quality was reporting 100% coverage...no violations for pep8 at the time. Even so, rendering the html report was problematic. 

For the build pasted above, the .report files are empty for pep8. That is normal in a pull request that is keeping our pep8 violations at zero.

**Comment by Bachmann1234** [comment] 2015-02-18 03:35
Hmm, this is a pickle

So I tried to recreate this by just using the diff in the PR (grabed platform and the remote. Went to that branch and ran diff) 

This was the report i got out.

https://gist.github.com/Bachmann1234/b7c67b6d7fb38e57880e

**Comment by benpatterson** [comment] 2015-02-20 13:53
Yeah that looks pretty a-ok. Sorry this is so hard to reproduce :( Maybe someone will check in a .exe and then we'll have another example :\

**Comment by Bachmann1234** [comment] 2015-02-21 21:30
@sarina @benpatterson so I was thinking. I could make a branch that simply wraps that line with a try catch to find out exactly what file is causing it to choke on your build server.

Also, it would unblock that PR since it would run

**Comment by sarina** [comment] 2015-02-25 15:17
We've decided to not let the quality issue actually block the PR. but would
be good at some point to fix this.

**Comment by Bachmann1234** [comment] 2015-02-25 15:20
@sarina alrighty. Ill make another attempt to reproduce this sometime this week.

**Comment by Bachmann1234** [comment] 2015-09-11 23:42
Its been a while, has this issue ever come up again?

**Comment by sarina** [comment] 2015-09-12 00:23
No but I suspect it's because we infrequently commit binary files.

**Comment by benpatterson** [comment] 2015-09-14 17:29
Same as @sarina . I haven't seen it, but haven't been seeing too many binaries come by. I've attempted to reproduce it a few times by creating tars, zips and whatnot, but no luck. It was consistently happening when I reported it--on multiple systems, etc. But...no dice otherwise.

**Comment by Bachmann1234** [comment] 2015-09-17 02:56
Odd, ok. Closing this now . If you ever find another example let me know.

**Closed by Bachmann1234** 2015-09-17 02:56 UTC
