### ISSUE TITLE
diff-cover fails with no message on Windows

### ISSUE THREAD

**Issue by evanunderscore** [Bachmann1234/diff-cover#17] opened 2015-09-12 09:29 UTC
Running `diff-cover` ends up calling `tool.py` which examines `sys.argv[0]` to see if it ends with `diff-cover` or `diff-quality`. For me, this is actually `C:\Python27\Scripts\diff-cover-script.py`, so nothing happens.

**Comment by Bachmann1234** [comment] 2015-09-12 21:07
Interesting! Ill look into this asap. Should be an easy fix

**Comment by Bachmann1234** [comment] 2015-09-12 21:47
Howdy! 

Can you give the new version a shot? https://pypi.python.org/pypi/diff_cover

The script should run now. I tested it on a Windows 10 environment. However I wanna set some expectations. All I did was ensure it runs. I am a bit worried there will be other issues due to the way paths work. Can you let me know if you have any other issues?

**Comment by evanunderscore** [comment] 2015-09-13 00:32
Thanks! This sorted it out.

I'm using this with luacov which gave me some odd output for my paths (like `.\src/test.lua`) so I had to do a little bit of post-processing and call `os.path.normpath` (to make `src\test.lua`). I haven't looked at how this works internally but if that's a simple fix for you that would be great.

**Comment by Bachmann1234** [comment] 2015-09-13 00:44
Sure! Ill look some time in the next couple days

**Comment by Bachmann1234** [comment] 2015-09-13 00:49
Is the project something you can share btw? Or at least the coverage report you used with diff-cover? Could help tracking this down.

**Comment by evanunderscore** [comment] 2015-09-13 01:30
It looks like it's expecting the paths with backslashes because GitPathTool calls `os.path.relpath` which will normalise the paths. I changed `clazz.get('filename') == src_rel_path` to `os.path.normpath(clazz.get('filename')) == src_rel_path` in `violations_reporter.py` and that seems to fix the problem for me.

I'm just using a test project to see if I can get bunch of tools working together. I'll fix it up with some instructions on how to reproduce the failure and push it up soon.

**Comment by evanunderscore** [comment] 2015-09-13 02:12
I've pushed up the test project to https://github.com/evanunderscore/gideros_coverage_test. The only thing you should need to run it is Python and Lua.

**Comment by evanunderscore** [comment] 2015-09-13 04:18
For reference, I'm running `git version 1.9.5.msysgit.0` (from cmd, not Git Bash).

**Comment by evanunderscore** [comment] 2015-09-13 04:37
Perhaps it would be nice to generate a list of all files in the repository and warn if any of the files in the coverage report aren't found. This would also give a more helpful message for the first issue in the troubleshooting section where the coverage report was generated from a different working directory.

**Comment by Bachmann1234** [comment] 2015-09-14 23:01
im not done looking at this yet, but I am seeing something that makes me think luacov has a bit of a problem

So the paths im seeing in the report are inconsistent 

```
<class line-rate="0.875" name=".\scripts\maths.lua" branch-rate="0" complexity="0" filename=".\scripts\maths.lua">
```

```
<class line-rate="1" name="test.lua" branch-rate="0" complexity="0" filename="tests/test.lua">
```

See how in one its \ and another its / ?

Which sounds like a bug in luacov. *However* I wanna see if I can deal with this inconsistency. I should be able to normalize the paths `os.path.normpath` (thanks for that btw, did not know about that one)

Also, thanks for the super clear reproduce steps. :-D

Below is the full coverage report for history 

```
<coverage line-rate="0.90909090909091" version="1.9" branch-rate="0" timestamp="1442271411000">
	<packages>
		<package line-rate="0.875" name="" branch-rate="0" complexity="0">
			<classes>
				<class line-rate="0.875" name=".\scripts\maths.lua" branch-rate="0" complexity="0" filename=".\scripts\maths.lua">
					<methods/>
					<lines>
						<line number="1" branch="false" hits="1"/>
						<line number="3" branch="false" hits="1"/>
						<line number="4" branch="false" hits="1"/>
						<line number="7" branch="false" hits="1"/>
						<line number="8" branch="false" hits="1"/>
						<line number="11" branch="false" hits="1"/>
						<line number="12" branch="false" hits="0"/>
						<line number="15" branch="false" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package line-rate="1" name="tests" branch-rate="0" complexity="0">
			<classes>
				<class line-rate="1" name="test.lua" branch-rate="0" complexity="0" filename="tests/test.lua">
					<methods/>
					<lines>
						<line number="1" branch="false" hits="1"/>
						<line number="3" branch="false" hits="1"/>
						<line number="4" branch="false" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
	<sources/>
</coverage>
```

**Comment by Bachmann1234** [comment] 2015-09-15 01:12
and the diff
```
diff --git a/scripts/maths.lua b/scripts/maths.lua
index d31c441..bcd11a9 100644
--- a/scripts/maths.lua
+++ b/scripts/maths.lua
@@ -8,4 +8,8 @@ function maths.subber(a, b)
 	return a - b
 end
 
+function maths.mult(a,b)
+	return a * b
+end
+
 return maths

```

**Comment by Bachmann1234** [comment] 2015-09-15 02:23
@evanunderscore this issue is fixed in this pr https://github.com/Bachmann1234/diff-cover/pull/19 im holding off a bit for release to see if diff-cover's major user wants to review it.

**Comment by evanunderscore** [comment] 2015-09-15 10:04
Thanks for the quick fix! This behaviour does seem to be a bug with luacov. It looks like it builds paths with the native separator but leaves any existing slashes alone. Regardless, diff-cover appears to be handling all cases now.

**Comment by evanunderscore** [comment] 2015-09-15 10:49
Had a quick look over the changes and left a couple of comments. Hope you don't mind.

**Comment by Bachmann1234** [comment] 2015-09-15 12:08
Of course not! It looks like you caught some sloppiness on my part

**Comment by Bachmann1234** [comment] 2015-09-15 14:12
Im going to close this, we are continuing the discussion on paths in the pr https://github.com/Bachmann1234/diff-cover/pull/19

and the issue that started this is fixed

**Closed by Bachmann1234** 2015-09-15 14:12 UTC

**Comment by backupProject** [comment] 2015-12-17 06:34
[regression]
The diff_cover-0.8.5 fails again with no message on Windows.
I have compared the code of diff_cover-0.8.5 and diff_cover-0.8.2, and the difference of 'diff_cover/tool.py' is as follow:
tool.py of diff_cover-0.8.2:
line-234 if 'diff-cover' in progname:

tool.py of diff_cover-0.8.5: 
line-234 if progname.endswith('diff-cover'):

I think diff_cover-0.8.5 should be same as diff_cover-0.8.2 for this line.

**Comment by evanunderscore** [comment] 2015-12-17 07:54
The problem is that this may or may not have the path and the `.py` extension. To do this properly it should probably use `os.path.basename` and `os.path.splitext`, and also print some kind of error message if it doesn't match a known name. I'm happy to submit a fix if you like.

**Comment by backupProject** [comment] 2015-12-18 02:05
Yes, it is a good idea to print some error message.
